spring.application.name=backend-practice

spring.datasource.url=jdbc:postgresql://localhost:5432/backend_practice
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
